# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.12'

target 'I2PLauncher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for I2PLauncher
  pod 'MBPopup'
  pod 'SnapKit'
  pod 'SwiftDate'
  pod 'Kanna'
end
