#
# This Makefile is compatible with GNU Make and should work on FreeBSD
#

#
# Your operating system
#

OS = FREEBSD

#
# Directories
#

INCDIR = inc
LIBDIR = lib
OBJDIR = obj
SRCDIR = src

#
# Programs
#

AR = ar
CC = gcc
RM = rm

#
# Flags
#

CFLAGS = -g -O2 -pipe -std=c99 -Wall
CFLAGS += -DOS=$(OS)
CFLAGS += -I$(INCDIR)

#
# Object files
#

OBJS =	$(OBJDIR)/sam.o

#
# Include the make instructions common to all platforms
#

include Makefile.common
