<h4><% if (request.getRequestURI().indexOf("config.jsp") != -1) { 
 %>Network | <% } else { %><a href="config.jsp">Network</a> | <% }
 if (request.getRequestURI().indexOf("configservice.jsp") != -1) {
 %>Service | <% } else { %><a href="configservice.jsp">Service</a> | <% }
 if (request.getRequestURI().indexOf("configupdate.jsp") != -1) {
 %>Update | <% } else { %><a href="configupdate.jsp">Update</a> | <% }
 if (request.getRequestURI().indexOf("configtunnels.jsp") != -1) {
 %>Tunnels | <% } else { %><a href="configtunnels.jsp">Tunnels</a> | <% }
 if (request.getRequestURI().indexOf("configlogging.jsp") != -1) {
 %>Logging | <% } else { %><a href="configlogging.jsp">Logging</a> | <% }
 if (request.getRequestURI().indexOf("configadvanced.jsp") != -1) {
 %>Advanced<% } else { %><a href="configadvanced.jsp">Advanced</a><% } %></h4>
