/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class freenet_support_CPUInformation_CPUID */

#ifndef _Included_freenet_support_CPUInformation_CPUID
#define _Included_freenet_support_CPUInformation_CPUID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     freenet_support_CPUInformation_CPUID
 * Method:    doCPUID
 * Signature: (I)Lfreenet/support/CPUInformation/CPUID$CPUIDResult;
 */
JNIEXPORT jobject JNICALL Java_freenet_support_CPUInformation_CPUID_doCPUID
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
