#!/bin/sh
#
# This launches i2psnark and jetty in a separate jvm.
# The file jetty-i2psnark.xml must be present in the current directory.
# i2psnark will be accessed at http://127.0.0.1:8002/
#
I2P="."
java -jar "$I2P/i2psnark.jar"
