.TH i2prouter 1 "April 19, 2012" "" "I2PROUTER"

.SH NAME
i2prouter \- start and stop the I2P router

.SH SYNOPSIS
.B i2prouter
.RI { console | start | stop | graceful | restart | condrestart | status | dump | install | remove }
.br

.SH DESCRIPTION
Control the I2P service.

.B
.IP console
Runs I2P as a console application under the current user.

.B
.IP start
Starts the I2P service.

.B
.IP stop
Stops the I2P service.

.B
.IP restart
Stops the I2P service and then starts it.

.B
.IP condrestart
Restart the I2P service only if it is already running.

.B
.IP graceful
Stop I2P gracefully (may take up to 11 minutes)

.B
.IP install
Install initscript to start I2P automatically when the system boots.

.B
.IP remove
Uninstall initscript that was installed with \fB install\fP

.B
.IP status
Prints whether the I2P service is running.

.B
.IP dump
Dumps the current threads into\fB wrapper.log\fP.
