#ifndef _I2P_ERRORS_H
#define _I2P_ERRORS_h


#define ERROR_COULDNT_LOAD_JVM 6
#define ERROR_COULDNT_PARSE_ARGUMENTS 7
#define ERROR_COULDNT_INITIALIZE_JVM 8
#define ERROR_STARTING_PROGRAM 9
#define ERROR_COULDNT_FIND_JVM 10

#endif /* _I2P_ERRORS_H */