#! /bin/sh

### BEGIN INIT INFO
# Provides:		i2p
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	
# Default-Stop:		1 2 3 4 5
# Short-Description:	I2P anonymizing mixnet
### END INIT INFO

set -e

. /lib/lsb/init-functions

function I2P {
	su i2p -c "/var/lib/i2p/i2prouter $1"
}

case "$1" in
  start)
	log_daemon_msg "Starting I2P" "i2p"
	if I2P start; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping I2P" "i2p"
	if I2P stop; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  restart)
	log_daemon_msg "Restarting I2P" "i2p"
	if I2P restart; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  status)
	I2P status
	;;

  *)
	log_action_msg "Usage: /etc/init.d/i2p {start|stop|restart|status}"
	exit 1
esac

exit 0
