#!/bin/sh
SVCHOME=/var/lib/i2p
I2P=/usr/share/i2p
I2PUSER=i2psvc

useradd -d $SVCHOME -r $I2PUSER
chown $I2PUSER:$I2PUSER $I2P -R
mkdir -p $SVCHOME
chown $I2PUSER:$I2PUSER $SVCHOME

update-rc.d i2p defaults

invoke-rc.d i2p start
