#!/bin/sh

I2PUSER=i2psvc
# delete $I2PUSER if it exists (it will not if this is a purge after a remove)
id $I2PUSER 2>/dev/null
if [ $? -eq 0 ]; then
    exec userdel $I2PUSER
fi

# if somebody did updates in-network, there may be new files that dpkg
# doesn't know about, so just to be sure
I2P=/usr/lib/i2p
rm -rf $I2P

