#!/bin/sh
SVCHOME=/var/lib/i2p
I2P=/usr/lib/i2p
I2PUSER=i2psvc

useradd -d $SVCHOME -r $I2PUSER
chown $I2PUSER:$I2PUSER $I2P -R
mkdir -p $SVCHOME
chown $I2PUSER:$I2PUSER $SVCHOME

update-rc.d i2p defaults

cd $I2P
su $I2PUSER ./postinstall.sh

chmod 755 /usr/lib/i2p/eepget
chmod 755 /usr/lib/i2p/i2prouter
chmod 755 /usr/lib/i2p/i2psvc

invoke-rc.d i2p start
