#!/bin/sh
/etc/init.d/i2p stop

# stuff in /tmp
TMPDIR=/tmp
rm -f ${TMPDIR}/wrapper.log ${TMPDIR}/wrapper.log.1 ${TMPDIR}/wrapper.log.2 ${TMPDIR}/i2p.pid ${TMPDIR}/routerjvm.pid ${TMPDIR}/router.ping

# dpkg doesn't know about these files, they were copied out of jbigi.jar by the router
LIB=/usr/lib/i2p
rm -f $LIB/libjbigi.so $LIB/libjcpuid.so

# the home directory for the i2p daemon
SVCHOME=/var/lib/i2p
rm -rf $SVCHOME

# if any user other than i2psvc has run i2p, the files in ~user/.i2p are not removed
exit 0
