#!/bin/sh
/etc/init.d/i2p stop

# stuff in /tmp
rm -f /tmp/wrapper.log /tmp/wrapper.log.1 /tmp/wrapper.log.2 /tmp/i2p.pid /tmp/routerjvm.pid /tmp/router.ping

# /etc/rc*.d/*i2p files	
update-rc.d -f i2p remove

# dpkg doesn't know about these files, they were copied out of jbigi.jar by the router
rm -f $I2P/libjbigi.so $I2P/libjcpuid.so

# the home directory for the i2p daemon
SVCHOME=/var/lib/i2p
rm -rf $SVCHOME

# if any user other than i2psvc has run i2p, the files in ~user/.i2p are not removed
exit 0
