#
# This Makefile is compatible with GNU Make and has Winsock linking
#

#
# Programs
#

CC = C:\Dev-Cpp\bin\gcc
RM = C:\Dev-Cpp\bin\rm

#
# Flags
#

CFLAGS = -g -O2 -pipe -std=c99 -Wall
CFLAGS += -DWINSOCK
CFLAGS += -I../../inc -L../../lib
LIBS = -lsam -lwsock32

#
# Include the make instructions common to all platforms
#

include Makefile.common
