#
# This Makefile is compatible with GNU Make and should work on POSIX systems
#

#
# Programs
#

CC = gcc
RM = rm

#
# Flags
#

CFLAGS = -g -O2 -pipe -std=c99 -Wall
CFLAGS += -I../../inc -L../../lib
LIBS = -lsam

#
# Include the make instructions common to all platforms
#

include Makefile.common
